# Generated by Django 3.1.4 on 2020-12-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0002_auto_20201220_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
